name: test-docker-compose
base_image: language/buster/node_14
team: devex
processes:
  web: &web_process
    cmd:
      - docker-compose up
    port: 3000
    ssl: false
    public: true
    external_domain_prefix: 'test-typesense'
    internal_domain_prefix: 'test-typesense'
